### ISSUE TITLE
[3D Model] Rigging and Animation Iris Model: Walking

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#318]

**Comment by ahmadhaydar** [comment]
![Animation1](https://user-images.githubusercontent.com/78914402/164499617-c96d6ccf-264a-419e-a9e8-5c524b366a0b.gif)
Note : model overlap is fixed

Actions:
1. Idle (160 Frames)
2. Walk Cycle (40 Frames x 4)

No Transitions has been animated (since it's a lot)

Link:
https://drive.google.com/drive/folders/1vrzW9EO-oOpfvMpO5R2s4N4ZHMMBeWqw
