### ISSUE TITLE
Select prefabs from Snaps that can be used

### ISSUE THREAD

**Issue by uciii** [InShine-Studios/Horror-3D#91]
- Office = [https://assetstore.unity.com/packages/3d/environments/snaps-prototype-office-137490](https://assetstore.unity.com/packages/3d/environments/snaps-prototype-office-137490)
- Industrial = [https://assetstore.unity.com/packages/3d/environments/sci-fi/snaps-prototype-sci-fi-industrial-136759](https://assetstore.unity.com/packages/3d/environments/sci-fi/snaps-prototype-sci-fi-industrial-136759)

**Comment by JahnsMichael** [comment]
Snaps, especially the Office Prototype came with many good meshes and prefab that match our 3d art style. Here are some previews.

- Videos

https://user-images.githubusercontent.com/60375650/150940285-3353afac-1ead-41b8-9d81-cf2e4116d53e.mp4

- Columns and Stairs
![01252022-152318](https://user-images.githubusercontent.com/60375650/150940348-9918d82a-ef20-482d-bc93-a06800da31d0.png)

- Doors and Walls
![01252022-152310](https://user-images.githubusercontent.com/60375650/150940360-485fe57a-fb26-4d53-b55b-627951985990.png)

- Small stuffs
![01252022-152300](https://user-images.githubusercontent.com/60375650/150940378-fbd142f7-8e7a-484c-b266-836d47a042a9.png)

- Light Sources
![01252022-152232](https://user-images.githubusercontent.com/60375650/150940401-4dfa48ca-1497-4ddd-a8f6-f3368cdab6b9.png)

- Room Decorations
![01252022-152151](https://user-images.githubusercontent.com/60375650/150940805-842925fe-cfc7-484d-8ce1-4d2978ac9240.png)

Visually, they match our needs and style and we can customize them further with custom materials and texture, but these prefabs include Level Structure Meshes such as Walls, Stairs, and Columns so I want to make sure to @InShine-Studios/designer-clan if you want to use it or not, given that there are already manually designed level.

**Comment by JahnsMichael** [comment]
For our concern, when we import Snaps, we can partially import some prefabs only but it isn't the best way because we want to preview it before we choose to use it, and we can't preview a prefab before we import it. 

Another way to partially use Snaps is by importing it to our local project but don't push it to the remote repo (with including the package directory to `.gitignore`), and then when we want to use some prefabs, we can copy that chosen prefabs to our Gameplay directory and then push it to the remote repo so then we only include used prefabs to our project. Which way do we prefer? (Note, I don't know the best practice for this case).

For more information, totally Snaps:
![01252022-154911](https://user-images.githubusercontent.com/60375650/150943598-9a1fa525-41f4-4d02-b1e1-8e22721d32bb.png)

I don't know if it is huge or not, but the other way is just to import the whole package.
